<?php
$config = [
    'use_page_numbers' => true,
    'full_tag_open'    => '<ul class="pagination">',
    'full_tag_close'   => '</ul>',
    'num_tag_open'     => '<li>',
    'num_tag_close'    => '</li>',
    'cur_tag_open'     => '<li class="active"><a href="#">',
    'cur_tag_close'    => '</a></li>',
    'prev_link'        => '&lt;',
    'prev_tag_open'    => '<li>',
    'prev_tag_close'   => '</li>',
    'next_link'        => '&gt;',
    'next_tag_open'    => '<li>',
    'next_tag_close'   => '</li>',
    'first_link'       => '&lt;&lt;',
    'first_tag_open'   => '<li>',
    'first_tag_close'  => '</li>',
    'last_link'        => '&gt;&gt;',
    'last_tag_open'    => '<li>',
    'last_tag_close'   => '</li>',
];